#
# Linux Makefile
#

CC = g++
LD = g++

CFLAGS = -D_REENTRANT -fpic -g
LDFLAGS = -lpthread

all : teststring1 teststring2 teststring3 teststring4 teststring5 teststring6 teststring7 teststring8 testmap

teststring1: teststring1.o
teststring2: teststring2.o
teststring3: teststring3.o
teststring4: teststring4.o
teststring5: teststring5.o
teststring6: teststring6.o
teststring7: teststring7.o
teststring8: teststring8.o

testmap: testmap.o

testmap.o: testmap.cpp
	$(CC) $(CFLAGS) -DMEM_ALLOC_DEBUG -c testmap.cpp

.cpp.o:
	$(CC) $(CFLAGS) -c $<

.o.:
	$(LD) $(LDFLAGS) $<

clean:
	-rm -f *.o

